// <auto-generated />
namespace Advance.Framework.ContactModule.Repositories.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removecascadedelete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removecascadedelete));
        
        string IMigrationMetadata.Id
        {
            get { return "201705280534251_remove cascade delete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
